project:
  type: website
  output-dir: docs

website:
  title: "Taylor Headland"
  favicon: Images/favicon.ico
  navbar:
    logo: Images/favicon-32x32.png
    right:
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: blog.qmd
        text: Blog
      - href: https://twitter.com/TaylorHeadland
        icon: Twitter
      - href: https://github.com/taylorheadland
        icon: github
  search: true
   

format:
  html:
    theme: 
    - yeti
    - custom_theme.scss
    css: styles.css
    toc: true
    code-block-border-left: true
    highlight-style: a11y
    code-block-bg: "#F4F7F3"
    fontsize: 1.19rem

editor: visual

