project:
  type: website
  output-dir: docs

website:
  title: "Taylor Headland"
  navbar:
    background: "#FFFFFF"
    foreground: "#FFFFFF"
    right:
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: blog.qmd
        text: Blog
      - href: https://twitter.com/TaylorHeadland
        icon: Twitter
      - href: https://github.com/taylorheadland
        icon: github
  search: true
   

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

