---
title: "Publications"
freeze: true
format: html
---

## 2021

Headland, T., Ostendorf, B., & Taggart, D. (2021) The behavioral responses of a nocturnal burrowing marsupial (*Lasiorhinus latifrons*) to drone flight. Ecology and Evolution, 11, 12173-- 12181. <https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.7981>

[Abstract]{.underline}

The use of drones in wildlife research and management is increasing. Recent evidence has demonstrated the impact of drones on animal behavior, but the response of nocturnal animals to drone flight remains unknown. Utilizing a lightweight commercial drone, the behavioral response of southern hairy-nosed wombats *(Lasiorhinus latifrons)* to drone flights was observed at Kooloola Station, Swan Reach, South Australia. All wombats flown over during both day and night flights responded behaviorally to the presence of drones. The response differed based on time of day. The most common night-time behavior elicited by drone flight was retreat, compared to stationary alertness behavior observed for daytime drone flights. The behavioral response of the wombats increased as flight altitude decreased. The marked difference of behavior between day and night indicates that this has implications for studies using drones. The behavior observed during flights was altered due to the presence of the drone, and therefore, shrewd study design is important (i.e., acclimation period to drone flight). Considering the sensory adaptations of the target species and how this may impact its behavioral response when flying at night is essential.

## 2023

Headland, T., Colombelli-Négrel, D., Callaghan, C.T. *et al.* Smaller Australian raptors have greater urban tolerance. *Sci Rep* **13**, 11559 (2023). <https://doi.org/10.1038/s41598-023-38493-z>

[Abstract]{.underline}

Urbanisation is occurring around the world at a rapid rate and is generally associated with negative impacts on biodiversity at local, regional, and global scales. Examining the behavioural response profiles of wildlife to urbanisation helps differentiate between species that do or do not show adaptive responses to changing landscapes and hence are more or less likely to persist in such environments. Species-specific responses to urbanisation are poorly understood in the Southern Hemisphere compared to the Northern Hemisphere, where most of the published literature is focussed. This is also true for raptors, despite their high diversity and comparably high conservation concern in the Southern Hemisphere, and their critical role within ecosystems as bioindicators of environmental health. Here, we explore this knowledge gap using community science data sourced from eBird to investigate the urban tolerance of 24 Australian raptor species at a continental scale. We integrated eBird data with a global continuous measure of urbanisation, artificial light at night (ALAN), to derive an urban tolerance index, ranking species from positive to negative responses according to their tolerance of urban environments. We then gathered trait data from the published literature to assess whether certain traits (body mass, nest substrate, habitat type, feeding guild, and migratory status) were associated with urban tolerance. Body size was negatively associated with urban tolerance, as smaller raptors had greater urban tolerance than larger raptors. Out of the 24 species analysed, 13 species showed tolerance profiles for urban environments (positive response), and 11 species showed avoidance profiles for urban environments (negative response). The results of this study provide impetus to conserve native habitat and improve urban conditions for larger-bodied raptor species to conserve Australian raptor diversity in an increasingly urbanised world.
