---
title: "Relative abundance of Wedge-tailed Eagles in Australia"
description: |
  Eagles are cool, so lets find out where and how many there are across Australia!
date: ""
title-block-banner: "#1434A4"
title-block-banner-color: "#ffffff"
categories: 
  - modelling
freeze: true
format: html
editor_options:
  chunk_output_type: console
---

Throughout the time that I've been undertaking my PhD I've gained skills in data science and statistical programming, particularly with the language R. I started learning R during my Honours year, but have been able to take it to the next level with my PhD in terms of the complexity and scope of use. Although daunting at times, learning to code has been the most enjoyable part of my PhD and something that I look forward to hopefully doing as part of a job sometime in the future!

In this article I'm going to estimate the relative abundance of the Wedge-tailed Eagle in Australia using data from the community science platform, eBird. This platform boasts a staggering 1.3 billion records of birds across the globe, and is an invaluable conservation resource to study bird populations and how they change across time and space. I decided on the Wedge-tailed Eagle, because as a birder that specifically studies raptors, you can't get much cooler than an Eagle!

This analysis largely follows the work of Matt Strimas-Mackey and the wonderful work that he and the eBird team at Cornell University in America put together in the form of a best practices guide when working with eBird data. This has been an extremely helpful resources throughout my PhD and I couldn't have done a few of my chapters without it! Here is a link to the resource: <https://ebird.github.io/ebird-best-practices/>

Enough chit chat, lets get to the analysis!

First up, lets load the packages and data required for the analysis.

```{r package and data loading, message=FALSE, warning=FALSE}
library(tidyverse) #tidy data/wrangling
library(auk) #eBird data wrangling
library(ebirdst) #spatiotemporal subsampling
library(gridExtra) #plotting
library(mccf1) # modelling
library(ranger) #modelling
library(scam) #modelling
library(sf) #spatial data operations
library(terra) #raster data operations
```

Lets also load in a shapefile of Australia so that we can make pretty look maps of our predictions.

Data within community science programs are often subject to spatial and temporal biases. Australia represents a fantastic example of spatial sampling bias, as illustrated below by the figure. The majority of eBird checklists fall into coastal areas where people live, instead of being evenly distributed across the landscape. Checklists also follow things like roads, which is evident by the line of checklists spanning the Stuart Highway from mid-South Australia up to the Northern Territory. People are usually more available on weekends to contribute to community science projects, and there are studies that document this 'Weekend effect'. To minimise these biases, we will perform spatiotemporal subsampling to the data by selecting a checklist for every week of the available data within a defined 3x3 km grid cell.

Lastly, we will select the predictors for the model and hold aside some of the data to for model testing

Now we are ready to model the data! We will use random forest models to achieve a prediction for the relative abundance of Wedge-tailed Eagles across Australia. The first model is a classification random forest that will achieve a measure of encounter rate, which is \_\_\_\_\_.
